DROP SEQUENCE seq_coupon;
DROP SEQUENCE seq_user;
DROP SEQUENCE seq_store;

DROP TABLE COUPON CASCADE CONSTRAINTS;
DROP TABLE USER_INFO CASCADE CONSTRAINTS;
DROP TABLE STORE CASCADE CONSTRAINTS;